### ISSUE TITLE
Imported models from Minecraft misplaced

### ISSUE THREAD

**Issue by Indianajaune** [iChun/Tabula#101]
I do not know if that's something specific to my setup (i run forge 1.12.2-2707 on JRE 1.8-171 using iChunutil 1.12.2-7.1.4 and Tabula 1.12.2-7.0.0)

![image](https://user-images.githubusercontent.com/16310778/41212424-1330ad1a-6d3e-11e8-9044-a98c6ff6e445.png)

Is there a way for me to fix this?

**Comment by iChun** [comment]
What's wrong with the model? Looks right to me.

**Comment by Indianajaune** [comment]
Don't you see the model is deformed,look at this 
![image](https://user-images.githubusercontent.com/16310778/41226011-7ee7a298-6d70-11e8-8234-368de699e565.png)
I also have the sameproblem with nearly all mobs except the cow...

For example zombie has his headnot displayed...
![image](https://user-images.githubusercontent.com/16310778/41226082-ad78646c-6d70-11e8-8177-60d7556e1743.png)

Maybe i am doing something not correctly? ( I am completely new to this mod i used Techne until now)

**Comment by iChun** [comment]
Those are the models. I see nothing wrong with them. The parts you're looking at are models with a blank texture so it shows up invisible. Click on it and delete it or move it.
