### ISSUE TITLE
Invisible Boxes 1.2.2-7.0.1

### ISSUE THREAD

**Issue by KilynnTor** [iChun/Tabula#105]
I'm liking some of the new tools. I did come upon a breaking issue though, the boxes are invisible! Before anyone asks, I checked the transparency settings.

Create new file> create box, is highlighted as selection>unselect, nothing to see.

Tabula-1.12.2-7.0.1.jar
iChunUtil-1.12.2-7.2.1.jar

**Comment by iChun** [comment]
Do you have any screenshots to help with debugging?

**Comment by KilynnTor** [comment]
Ok, I found the issue and it's Twitch's fault, it had 2 versions of each mod installed while telling me it only had 1 of each. I have not been feeling well, so didn't think to check the actual folders yesterday. Twitch finally showed it had 2 each installed after I closed it several times because it's been having an issue showing I have Minecraft installed at all and it had switched my java (I have to have a newer version installed for something else). I deleted the old ones by hand. It works fine now so far.

This can be closed, you may want to leave it in case someone else using twitch has this issue.

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
