### ISSUE TITLE
Ctrl + Z and Ctrol + Y both map to Undo

### ISSUE THREAD

**Issue by CammiePone** [iChun/Tabula#106]
As the title says, when using the Undo/Redo keyboard shortcuts, both act as if you're trying to do the Undo shortcut.

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.

**Comment by CammiePone** [comment]
No worries, and that's entirely understandable. Hope you have a good weekend!
