### ISSUE TITLE
Texture Glitch

### ISSUE THREAD

**Issue by Cryptillian** [iChun/Tabula#107]
When there are rotated cubes attached like the model shown (seen at the eye), they kinda glitch out. I was wondering if there is or if there will be a fix for this?
![hhhd](https://user-images.githubusercontent.com/52714644/60909269-cf8ecd00-a24b-11e9-9456-503803e74e3d.PNG)

**Comment by zeroxthreef** [comment]
The cubes are z-fighting. Try making one of them a little bit smaller.

**Comment by iChun** [comment]
^ z-fighting, every dev's rendering nightmare.

As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
