### ISSUE TITLE
[Suggestion] You should add a rotate model (entire model) button

### ISSUE THREAD

**Issue by Cobble8** [iChun/Tabula#109]
**I was working on my entity. Then tried to use it not realizing that I made it facing the wrong direction. Now I have to remake the entire model again. Instead of simply pushing a button. I think this would be useful for people who are just learning your mod.**

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
