### ISSUE TITLE
"Failed to open file" message when I try to open a TBL file in Tabula (log included)

### ISSUE THREAD

**Issue by cipherzerox** [iChun/Tabula#110]
I'm not sure what's causing this, but I figured I'd report it here: https://pastebin.com/Uaz5sznW

**Comment by iChun** [comment]
It looks like Tabula is having issues reading or accessing your file. It
could be an access issue or possibly a corrupted file. Are you able to save
new projects or open other files fine?

**Comment by cipherzerox** [comment]
Yeah I can open other files fine, weird enough.

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
