### ISSUE TITLE
How to export animation?

### ISSUE THREAD

**Issue by xwm850565206** [iChun/Tabula#111]
I use Tabula-1.12.2-7.1.0 and it provide animation function, but when I finish the design of animation, What should I do to export the animation?  thanks.

**Comment by iChun** [comment]
Unfortunately the animation feature of Tabula never really gained any
traction, so it has been scrapped. It's mentioned in the popup when you
launch Tabula and open the animation tab for the first time (in the latest
version) that it is no longer supported. However, the animations are still
saved to the tabula file and you are free to write your own interpreter or
feel free to submit a pull request of your own exporter for the animations.
At this point they are left in the workspace purely for legacy reasons.

**Comment by xwm850565206** [comment]
thanks, your mod is very helpful for me!
