### ISSUE TITLE
Armor models from otakucraft don't show up but the entities do

### ISSUE THREAD

**Issue by Draig666** [iChun/Tabula#112]
Hey is it supposed to show armor models because entities from the otakucraft mod show up but the armors don't and there is a 3d armor I would use as a base for my own mod, if there is no feature for this issue please add it to any existing versions of this mod. please and thankyou.

**Comment by iChun** [comment]
To start off: Putting stuff in caps in the title doesn't make it any more important, particularly when you are not a contributor or owner of the repository. It is misleading and frankly quite clickbaity for anyone else browsing the issues.

**Comment by iChun** [comment]
Support for 3rd party (eg mods) models are from reading all the render classes from memory. Classes referenced that have a readable model will be added to the list in Tabula.

If the model doesn't use the conventional Minecraft model and uses something such as obj3d files, Tabula will not read them. It is not what Tabula is made for. I am going to go on the off chance that this is the case for the mod you have trouble with. 

If they *aren't* obj3d models then, it's possible that they are only adding the models too late in the mod life cycle. Though not generally recommended, the mod may have their own reasons to do so. 

As said, I suspect its an obj3d thing, and Tabula is not written to support them (and never will). Closing.

**Comment by Draig666** [comment]
Just to say I've check lots of times not with tabula but with others sources and it is a model_welsh.class thats why I've turned to you

**Comment by iChun** [comment]
You have the option of decompiling the class if the source isn't available.
