### ISSUE TITLE
please read ichun.

### ISSUE THREAD

**Issue by Draig666** [iChun/Tabula#113]
First sorry for the Miss leading topic before. Second I've checked with other sources to find that the model is model_welsh.class. other model classes show up but that armor one doesn't. I would like your help with this. Thanks for reading this after the Miss leading clickbaity topic before. Future thing to maybe add is a feature that allows you to scan inside the jar files of mods for models and such. I don't have any coding for this because I'm a novice when it comes to coding that's why I turned to you for help.

**Comment by iChun** [comment]
There was no need to create a new issue for this. I've already told you what I can on the other issue.

**Comment by Draig666** [comment]
Just wanted to say sorry for Miss leading constant.
