### ISSUE TITLE
Crash when opening a model

### ISSUE THREAD

**Issue by Coda1552** [iChun/Tabula#119]
Hello! I have used Tabula for a long time and I am super thrilled you have updated it. I opened a model I made recently using the 1.12.2 version of Tabula, and it crashed. I've opened a few more models just fine, but after opening this one, it crashes the game. I've tried a few times. Here's the report: https://hastebin.com/atezufegal.rb

**Comment by iChun** [comment]
Should be fixed in 8.0.1. Thanks for the report!
