### ISSUE TITLE
Crashed when I tried to open a model using the Tablet

### ISSUE THREAD

**Issue by TheRebelT** [iChun/Tabula#120]
I've crashed when I tried to open using the tablet and then when I tried to run the game again, it crashed the game before getting onto the main title screen. Here's both crashes:
https://pastebin.com/ibMBEWLd
https://pastebin.com/3AF9gAUd

**Comment by iChun** [comment]
Should be fixed in 8.0.1. Thanks for the report!

**Comment by iChun** [comment]
PS: Not too sure about the second crash, that looks like it's FML related rather than Tabula related.
