### ISSUE TITLE
JEI Tooltip Error

### ISSUE THREAD

**Issue by WenXin20** [iChun/Tabula#121]
`Minecraft v1.15.2`
`Forge v31.2.19`
`Tabula v8.0.0`
`JEI v6.0.2.6`

After searching for the Tabula item in JEI, the item displays a red error text that tells me to view the log.
This is the error: https://gist.github.com/WenXin20/b180c3b1ca978297a7a2cf01124703cb

**Comment by iChun** [comment]
Brought this up with Project MMO. It will be fixed on their end.

**Comment by WenXin20** [comment]
Thanks!
