### ISSUE TITLE
Button Issues

### ISSUE THREAD

**Issue by WenXin20** [iChun/Tabula#122]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Tabula v8.0.1`

The first issue that I've noticed is that the button on the main menu doesn't have its position locked, so it can look awkward in certain window sizes:
![2020-07-16_00 30 48](https://user-images.githubusercontent.com/12000593/87631129-5cd8ed00-c6fc-11ea-8bab-a57b11676517.png)

The second is that the editor button has some white pixels that are not properly colored, probably some semi-transparent pixels that were not removed from the icons.
![2020-07-16_00 33 17](https://user-images.githubusercontent.com/12000593/87631180-82fe8d00-c6fc-11ea-9818-5f10e056fde5.png)

The third is that the tooltip doesn't display correctly, they all have "/Tooltip Items" in the tooltip and the furnace icon also overlaps them, as seen in the image above.

A search bar could also be useful, as when there are other mods installed, it is quite difficult to find a specific model in Minecraft. 
Thanks!

**Comment by IvorAmlug** [comment]
Do you have any other mods installed?

**Comment by WenXin20** [comment]
The one that adds the q button is from Quark, and the golem model is from Extra Golems.

**Comment by IvorAmlug** [comment]
The main menu is from LOTR am i right? It looks a lot like it

**Comment by IvorAmlug** [comment]
if so Try deactivating the custom main menu. i had some issues with Lotr its in a very early stage and had to take it out of my modlist.
The config file should be in whereyouinstalledyourminecraft/config

**Comment by IvorAmlug** [comment]
Is lotr even installed? tell me if it worked or you need any help

**Comment by WenXin20** [comment]
It is, but it doesn't have a config file yet. Although I'm pretty sure that the main menu is only a texture change

**Comment by IvorAmlug** [comment]
you have a mods button in your main menu you can change the config of some mods there. Its worth a try.

**Comment by IvorAmlug** [comment]
The config you search for should be named something like: Custommainmenu

**Comment by WenXin20** [comment]
There isn't a file named custommainmenu. And 1.15.2 doesn't have an in-game config yet.

**Comment by IvorAmlug** [comment]
wait a sec let me check that
Also its not a file its a option/line in the config

**Comment by WenXin20** [comment]
The 1.15.2 version of Lotr doesn't have a config yet.

**Comment by IvorAmlug** [comment]
okay just to see if its the issue take it out of your mods... so the custom main menu gets deactivated

**Comment by IvorAmlug** [comment]
The goal i to get the main menu to the vanilla design

**Comment by WenXin20** [comment]
Hmm, interesting. It looks like it is being caused by LOTR, probably because of the extra text it has on the screen. The interesting thing is that the Quark button isn't affected.
[Link](https://lotrminecraftmod.fandom.com/wiki/Updates/Renewed) to the Lotr mod for reference.
Thanks for the help to isolate that issue!

**Comment by IvorAmlug** [comment]
no problem Lotr is in a very early stage... as soon as you find/the mod gets a config file open it and deactivate main menu of Lotr

Stay safe.

**Comment by iChun** [comment]
Button height should be fixed in the 1.16.1 version, let me know if it's not! Search bar also added in the 1.16.1 version

**Comment by WenXin20** [comment]
Thanks!
