### ISSUE TITLE
Texturing issue. Textures get invisible.

### ISSUE THREAD

**Issue by IvorAmlug** [iChun/Tabula#123]
-Minecraft 1.15.2
-Forge v31.2.31
-Tabula v.8.0.1

So i know its better to use the texture of set funktion for tabula textures but it dosnt matter how i lay them out it keeps looking something like this:
![2020-07-17_13 42 45](https://user-images.githubusercontent.com/38656481/87782767-69ac2c80-c833-11ea-9554-257d8c4263e2.png)

Some textures get invisible for example the right arm or the left side of the neck
Anyone got any ideas how to fix this?

**Comment by iChun** [comment]
Having the model file would help debug if you don't mind sharing it

**Comment by IvorAmlug** [comment]
of course not:

[Modelfile.zip](https://github.com/iChun/Tabula/files/4942157/Modelfile.zip)
If put it in the zip. I hope thats okay

**Comment by iChun** [comment]
Scratched my head a bit but my chat and I found the problem. You're using partial dimensions (non-integer dimensions). Although Minecraft code itself has support for that, the way textures work, at a base level of x128 texture, does not. For the texture to support partial dimensions, you need to up the texture resolution to match the division count. So eg a 1.30 voxel will need the texture to be upped to x1280 (but MC won't like you very much for using a 1280x1280 texture, but that's the only way around it)
