### ISSUE TITLE
1.12 model in 1.15 

### ISSUE THREAD

**Issue by Accentaur** [iChun/Tabula#124]
so  i have a model that did not have anything in the old version that the new version doesn't have anymore do i just have to rebuild it

**Comment by IvorAmlug** [comment]
try to load it and see. worked out for me so far

**Comment by iChun** [comment]
I tried my best to transfer the old version models to the new version
models (Tabula project version 4 to 5).

It depends on how the models were built in old tabula, whether or not it
transfers over. Is it loading correctly on 1.15?
