### ISSUE TITLE
1.16 tabula is incompatiable with 1.15.2 models

### ISSUE THREAD

**Issue by Inonedn** [iChun/Tabula#125]

**Comment by iChun** [comment]
Does it like, crash or something? I'm trying to figure out this issue. https://github.com/iChun/Tabula/issues/126

**Comment by iChun** [comment]
I'm presuming this is the same issue as #126, since Tabula was practically unusable for anything that involved a project at the time. Will mark this as resolved, fixed in 9.0.1. Feel free to reopen if that's not the case.
