### ISSUE TITLE
[1.16.1] Crash when opening a mobs model

### ISSUE THREAD

**Issue by AzureDoom** [iChun/Tabula#126]
Tabula Version: 9.0.0
Forge Version: 32.0.67

Seems to happen whenever I try to open a mobs model

Crash Log: 
https://gist.github.com/AzureDoom/f2f54eb9529b0c1f40cda5ac3f4bf226

**Comment by AzureDoom** [comment]
Please note this happens with ANY model from vanilla to modded.

**Comment by iChun** [comment]
Could you please try out 9.0.1 (available on CF) and let me know how it goes?

**Comment by AzureDoom** [comment]
![image](https://user-images.githubusercontent.com/7415711/88746909-a4f40880-d11b-11ea-8973-7ce0b5702cc6.png)
Works perfectly! Thanks @iChun!
