### ISSUE TITLE
troubleshooting guide for 1.12 model porting (request)

### ISSUE THREAD

**Issue by kuroyure** [iChun/Tabula#129]
i did a heckton of models in the 1.12 version, lots of complex ones at that, and would like to know what parts of the model need the good ol ban hammer so i can salvage its parts, so could you add before loading the model, a list of what it has that you stopped supporting?

**Comment by iChun** [comment]
Mainly animations have been scrapped. I remember there was something else
that didn't make the refractor but I'm not too sure at this point in time.
Anything particularly complex you did with your model? I reckon your best
bet would be to try to load the model in the 1.15+ version of Tabula and
see what's different.
