### ISSUE TITLE
[CF Suggestion] Adding 1.16.5 to supported versions of the latest 1.16 build.

### ISSUE THREAD

**Issue by AzureDoom** [iChun/Tabula#132]
Hey just thought I'd create an issue to see if you would be able to add 1.16.5 to supported versions of the latest build. https://www.curseforge.com/minecraft/mc-mods/tabula-minecraft-modeler/files/3062126 it's currently unseachable on the CF API in 1.16.5. Thanks!

**Comment by iChun** [comment]
Thanks for letting me know. I'm working on an update involving four different mods currently and Tabula is one of them, when that is updated it'll be for 1.16.5.

**Comment by iChun** [comment]
"Fixed" since there's been new releases since.
