### ISSUE TITLE
[Future plan]Mouse editinig

### ISSUE THREAD

**Issue by anti344** [iChun/Tabula#23]
Deleted my comment from your future plans list =P

Drag sides of a box to increase/decrease it's size in that direction? With @Vswe method, you can fake-render each quad in a different color to determine, what side you select.

Also move boxes with a mouse, but i dont event know, how(since mouse is 2D and boxes is in 3D space).

**Comment by Vswe** [comment]
There is apparently some confusion about what this suggestion actually is. Here is however a short demo of something I've been working on: https://www.youtube.com/watch?v=H3rXq-Z1KmI . I am aware of that it's probably not what has been requested.

**Comment by anti344** [comment]
Thats almost exactly what i want.
Moving your mouse instead of clicking would be even better, but as you said it's tricky to calculate.

**Comment by Vswe** [comment]
I thought about doing it by moving the mouse at first as well. However, I doubt its worth it for 2 reasons:
1. You can just change the size in integer steps anyways, each click changes the size as little as possible.
2. It's tricky to calculate which size the user want.

**Comment by anti344** [comment]
Ok, i get it. And the same you can do with moving, just change position instead of size.
And for the sake of completeness we can do the rotations too.
I think calculation for rotation is simple - just add/subtract hypot of mouse deltas on selected axis.
The only problem now is to select axis =P

**Comment by Vswe** [comment]
It looks like you won't get any of that (including the size changer). iChun didn't like the approach so he'll implement something different at a later date.

**Comment by anti344** [comment]
Well, i can't think of any 3d editor (except Techne) that can't do that. And i (and probably a lot of users) was missing this a lot when using Techne. And since iChun did a lot of things that Techne was missing already, i hope he will do something like this, it's a lot easier that modifying positions and stuff by hands.

**Comment by iChun** [comment]
I'm having trouble getting the model to rotate/change size following the vector of the plane(s) and mouse movement. Would it be sufficient if I have it done that if the player were to drag to the right/up to increase the value, left/down to decrease the value?

**Comment by Vswe** [comment]
That won't really work, it's really confusing when the values gets inverted just because the camera is rotated.

**Comment by iChun** [comment]
I'm gonna have to let someone have a go at it eventually then. I'm pretty much done for tonight and done with the dragging code in general

**Comment by anti344** [comment]
@Vswe I didn't quite get your floating-point trickery, so i used bytes, and it worked perfectly for me.
```scala
def renderCube(quadConfig: => Unit) = {/*...*/}
var quadID = 0
renderCube{
  glColor3b(quadID.toByte, 1, 1)
  quadID += 1
}
val buffer = BufferUtils.createByteBuffer(3)
glReadPixels(Mouse.getX, Mouse.getY, 1, 1, GL_RGB, GL_BYTE, buffer)
val selected = buffer.get(0)
glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
quadID = 0
renderCube{
  if(selected == quadID)
    glColor3d(darkerBlueish._1, darkerBlueish._2, darkerBlueish._3)
  else glColor3d(blueish._1, blueish._2, blueish._3)
  quadID += 1
}
```
And renderCube is method that takes a block of code and renders some amount of polygons(6 for cube here) and applies this block right before rendering each polygon.
And if you use not only the red channel, then i an have 2^24-1 variations avaible.

**Comment by anti344** [comment]
![image](https://cloud.githubusercontent.com/assets/3393390/5598561/6a2739b4-92c1-11e4-83fb-b53de9291bb3.png)

**Comment by Vswe** [comment]
Huh? Not sure what you're talking about. I got my code to work perfectly too, iChun just didn't like it.

**Comment by anti344** [comment]
I mean using bytes is simpler, and it worked for me on the first try

**Comment by Vswe** [comment]
Using floats gives more control, and it worked for me on the first try. 

Using bytes or floats is completely off topic to this issue.
