### ISSUE TITLE
Unnecessary low event priority

### ISSUE THREAD

**Issue by lumien231** [iChun/Tabula#30]
Due to the lowest event priority here https://github.com/iChun/Tabula/blob/master/src/main/java/us/ichun/mods/tabula/common/core/EventHandler.java#L23

other mods that wanna do something with ALL buttons in the main menu are not able to modify the Tabula button.

**Comment by iChun** [comment]
Fixed https://github.com/iChun/Tabula/commit/bc32d1d83e6900be0c8e1132bec48512fabeb91c
