### ISSUE TITLE
[Idea] Select new box

### ISSUE THREAD

**Issue by BluSunrize** [iChun/Tabula#32]
When copy- and pasteing a box, have it select the new one instead of the old one? =3

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.

**Comment by BluSunrize** [comment]
Don't worry, haha. This is *very* old, an I've long since moved to obj for my modeling =P
