### ISSUE TITLE
Animations Code

### ISSUE THREAD

**Issue by Gekens** [iChun/Tabula#33]
When will be available the system to create the code of animation?

**Comment by iChun** [comment]
I'm still looking for feedback on the animations UI so I don't wanna finalize things just yet.

**Comment by Gekens** [comment]
Update about animations?

**Comment by iChun** [comment]
It'll probably be done alongside with the release of Hats for MC 1.8. That won't be anytime soon unfortunately.

**Comment by iChun** [comment]
Unfortunately I never got into having code that handles Animations, and from what I understood there were some other libraries that handled transitioning Tabula models. However, the Tabula format was redone for 1.15+ and animations ended up being stripped. No word on if they'll make a comeback or not but I have no plans on bringing them back. In case you were wondering what happened in regards to this 6+ year issue.

As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
