### ISSUE TITLE
'-' Sign crashes game

### ISSUE THREAD

**Issue by Seremis** [iChun/Tabula#35]
When I try to enter a negative number in the position field of a box, but accidentally hit enter after typing in only the '-' sign, the game crashes because Java doesn't know how to interpret it. Could you please add a catch for this?

Crash Log: http://pastebin.com/WycYC4RY

**Comment by iChun** [comment]
It will be fixed in the 1.8 version of the mod

**Comment by Seremis** [comment]
Ok, thanks

**Comment by iChun** [comment]
This issue has already been fixed in iChunUtil for MC 1.8
