### ISSUE TITLE
From BDcraft Cubik to Tabula ?

### ISSUE THREAD

**Issue by mariodk** [iChun/Tabula#36]
a Cubik to Tabula converter?

so we can get models we made in Cubiks or even made in blender or 3ds max becuase of Cubiks can get models from .Obj 
so from Cubik to Tabula will be amazing for modders or for people who making stuff for the WearMC mod (basically 3d skins/add or replace stuff on player model) mod
so .Obj(blender or 3ds max or other)>Cubik>Tabula>WearMC maybe?

also both nearly using same file format: .Json

this is needed (for minecraft v1.7.10 since wearMC is for that)

**Comment by laz2727** [comment]
Tabula only works with cubes, unlike most things out there - since Tabula
is a rewrite of Techne, and either there were limitations back then or
people wanted Techne to only work with cubes.

**Comment by mariodk** [comment]
i know that but Cubik convert things from obj to cubes thats why im asking for this

**Comment by Sphax84** [comment]
An export to JSON compatible with Tabula and WearMC is planned in Cubik ;)
