### ISSUE TITLE
Animation API Integration - Suggestion

### ISSUE THREAD

**Issue by BobMowzie** [iChun/Tabula#39]
It seems fairly clear that the exporter will eventually use f and f1 in setRotationAngles to export walking animations as equations, as is traditional in Minecraft. However, what will become of keyframe-based animations for other entity behaviors, such as attacks?

The exporter could convert these animations into the Animation API's format. The Animation API was developed by thehippomaster21, and allows for keyframe-based animations triggered by the entity's AI.
The forum topic can be found here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289836-animationapi-animate-your-entities-v1-2-3
The format for animations in the model can be found here: http://animationapi.wikia.com/wiki/Animating_the_Model

Of course, mods using these animations would become dependent on the API, but how else will they achieve the level of complexity that they desire?

**Comment by iChun** [comment]
thehippomaster21, man, that's a name I haven't heard in years.

As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
