### ISSUE TITLE
Copying parented pieces makes them immovable

### ISSUE THREAD

**Issue by FiskFille** [iChun/Tabula#49]
If you copy a piece that has other pieces parented to it, the copied pieces become "ghost-pieces". They're there, but you can't change any of their properties. You can't change rotation, position, texture mapping, etc.

**Comment by iChun** [comment]
1.8 or 1.7 version? Also an issue like this doesn't justify being Oi-ed at :(

**Comment by FiskFille** [comment]
1.7.10, latest version of Tabula. The reason I Oi-ed you is because in the Transformers mod we use Tabula for modeling, and it can get quite frustrating for our modeler. :)

**Comment by iChun** [comment]
I'll look into it when I can, really busy at the moment, but if you can build a 1.8 version for him to use instead, that'll be great.
