### ISSUE TITLE
Empty Field Crash/File Corruption

### ISSUE THREAD

**Issue by BobMowzie** [iChun/Tabula#50]
Though I cannot recall which parameter, I accidentally set a box's value to an empty string. I'm fairly certain that it was one of the dimensions. Tabula promptly crashed with this report:
http://pastebin.com/5xRDJ5aL

Upon trying to load the affected model after the crash, Tabula crashes with this report:
http://pastebin.com/8RrBvR7f

Somehow the problematic changes were saved to the .tbl file, because the file is corrupted. I would greatly appreciate a catch for inputting an empty string.

Thank you!

**Comment by gegy1000** [comment]
Also happens when you input something with non-numbers, eg 124DSF

**Comment by BobMowzie** [comment]
Strange. The second crash has something to do with the guy windows. I accidentally moved the model tree and caused that same crash. Opening the model again or any of its autosaves afterward causes the crash. However, if I close the model tree before opening the model, everything works.

The only problem is that now I don't have a model tree.

**Comment by BobMowzie** [comment]
Texture offsets will not save on affected models.

**Comment by iChun** [comment]
I really need to release the fixed version of this for MC 1.8...

**Comment by iChun** [comment]
This issue has already been fixed in iChunUtil for MC 1.8
