### ISSUE TITLE
Rendering issue - Transparent components hide all textures behind it

### ISSUE THREAD

**Issue by Drullkus** [iChun/Tabula#53]
So I'm trying to overlay a cuboid with 100% transparent parts but it completely hides the cuboid underneath it. :(

Here's what I see:

![screen shot 2015-03-24 at 3 28 45 pm](https://cloud.githubusercontent.com/assets/5010174/6814312/ba40aac6-d23a-11e4-96f1-f4e83f763b92.png)

What's underneath it:

![screen shot 2015-03-24 at 3 28 39 pm](https://cloud.githubusercontent.com/assets/5010174/6814305/b120f2b6-d23a-11e4-98d7-6066b4f475ed.png)

**Comment by Drullkus** [comment]
Better picture

![2015-03-25_08 58 58](https://cloud.githubusercontent.com/assets/5010174/6841216/b25756e8-d343-11e4-9b0a-fb87efdb5d98.png)

**Comment by iChun** [comment]
To be honest I'm not very sure how to fix this issue. It's also very
obvious when you pull in the new player models in 1.8

**Comment by Drullkus** [comment]
Upon further experimentation, this error happens when transparent objects are set after the objects that are visually behind it are set.

Observe:

The Glass Lens on this model are the cuboids that are set at the top of the stack in the box to the right of the Tabula GUI. Note that the frames are not rendered.

![screen shot 2015-03-25 at 8 49 23 pm](https://cloud.githubusercontent.com/assets/5010174/6848626/8fe9e4de-d38b-11e4-84c9-c7ac312f6b60.png)

Here's the version where the len cuboids are set at the bottom of the stack unlike the above image. Note that the frame behind it is rendered.

![screen shot 2015-03-25 at 8 53 56 pm](https://cloud.githubusercontent.com/assets/5010174/6848665/d265c2e2-d38b-11e4-98cc-87a29d0aaa21.png)

**Comment by iChun** [comment]
I'm aware. I unfortunately made the wrong decision of reverse order
rendering when making Tabula. It'll be a lot harder at this stage to swap
the render order around (I think).

**Comment by Drullkus** [comment]
Heyo! Just checking in. I ran into this issue... and forgot I already reported it already.

**Comment by iChun** [comment]
Hey @Drullkus! Yep, still not fixed, sorry :( It's all about render passes, and, well, Tabula straight up has no support for it, oof.

As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
