### ISSUE TITLE
Tabula crashes when you open a model

### ISSUE THREAD

**Issue by PCAwesomeness** [iChun/Tabula#59]
I constantly get this crash when I open a model. Any help?

---- Minecraft Crash Report ----
// Why is it breaking :(
Time: 4/26/15 8:42 PM
Description: Rendering screen
java.lang.NoSuchMethodError: us.ichun.mods.ichunutil.common.module.tabula.common.project.ProjectInfo.repair()V
 at us.ichun.mods.tabula.client.gui.window.WindowOpenProject.elementTriggered(WindowOpenProject.java:90)
 at us.ichun.mods.ichunutil.client.gui.window.element.ElementListTree.triggerParent(ElementListTree.java:299)
 at us.ichun.mods.ichunutil.client.gui.window.element.ElementListTree$Tree.draw(ElementListTree.java:528)
 at us.ichun.mods.ichunutil.client.gui.window.element.ElementListTree.draw(ElementListTree.java:122)
 at us.ichun.mods.ichunutil.client.gui.window.Window.draw(Window.java:130)
 at us.ichun.mods.tabula.client.gui.window.WindowOpenProject.draw(WindowOpenProject.java:58)
 at us.ichun.mods.ichunutil.client.gui.window.IWorkspace.drawWindows(IWorkspace.java:142)
 at us.ichun.mods.tabula.client.gui.GuiWorkspace.func_73863_a(GuiWorkspace.java:511)
 at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:461)
 at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1078)
 at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1048)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
 at net.minecraft.client.main.Main.main(SourceFile:120)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
 at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
 at org.multimc.EntryPoint.listen(EntryPoint.java:165)
 at org.multimc.EntryPoint.main(EntryPoint.java:54)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Stacktrace:
 at us.ichun.mods.tabula.client.gui.window.WindowOpenProject.elementTriggered(WindowOpenProject.java:90)
 at us.ichun.mods.ichunutil.client.gui.window.element.ElementListTree.triggerParent(ElementListTree.java:299)
 at us.ichun.mods.ichunutil.client.gui.window.element.ElementListTree$Tree.draw(ElementListTree.java:528)
 at us.ichun.mods.ichunutil.client.gui.window.element.ElementListTree.draw(ElementListTree.java:122)
 at us.ichun.mods.ichunutil.client.gui.window.Window.draw(Window.java:130)
 at us.ichun.mods.tabula.client.gui.window.WindowOpenProject.draw(WindowOpenProject.java:58)
 at us.ichun.mods.ichunutil.client.gui.window.IWorkspace.drawWindows(IWorkspace.java:142)
 at us.ichun.mods.tabula.client.gui.GuiWorkspace.func_73863_a(GuiWorkspace.java:511)
 at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:461)
-- Screen render details --
Details:
 Screen name: us.ichun.mods.tabula.client.gui.GuiWorkspace
 Mouse location: Scaled: (140, 16). Absolute: (280, 447)
 Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
-- Affected level --
Details:
 Level name: MpServer
 All players: 1 total; [EntityPlayerSP['PCAwesomeness'/512, l='MpServer', x=239.85, y=64.00, z=234.81]]
 Chunk stats: MultiplayerChunkCache: 361, 361
 Level seed: 0
 Level generator: ID 00 - default, ver 1. Features enabled: false
 Level generator options: 
 Level spawn location: 236.00,64.00,248.00 - World: (236,64,248), Chunk: (at 12,4,8 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
 Level time: 33859 game time, 41906 day time
 Level dimension: 0
 Level storage version: 0x00000 - Unknown?
 Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
 Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
 Forced entities: 117 total; [EntitySpider['Spider'/275, l='MpServer', x=223.50, y=41.00, z=178.50], EntityCreeper['Creeper'/274, l='MpServer', x=217.50, y=41.00, z=177.50], EntityCreeper['Creeper'/273, l='MpServer', x=220.50, y=40.00, z=175.50], EntityWitch['Witch'/272, l='MpServer', x=223.50, y=43.00, z=155.50], EntitySheep['Sheep'/279, l='MpServer', x=208.47, y=69.00, z=288.31], EntityPig['Pig'/278, l='MpServer', x=211.50, y=68.00, z=286.50], EntityPig['Pig'/277, l='MpServer', x=221.69, y=67.00, z=286.47], EntityCreeper['Creeper'/276, l='MpServer', x=222.00, y=31.00, z=182.38], EntityPig['Pig'/280, l='MpServer', x=212.06, y=68.00, z=293.28], EntitySkeleton['Skeleton'/258, l='MpServer', x=198.34, y=72.00, z=289.19], EntitySkeleton['Skeleton'/259, l='MpServer', x=197.50, y=68.00, z=296.50], EntitySheep['Sheep'/256, l='MpServer', x=202.06, y=68.00, z=292.06], EntityPig['Pig'/257, l='MpServer', x=203.50, y=68.00, z=291.16], EntityPig['Pig'/260, l='MpServer', x=192.47, y=84.00, z=296.69], EntityCreeper['Creeper'/305, l='MpServer', x=232.50, y=70.00, z=163.50], EntitySquid['Squid'/304, l='MpServer', x=236.38, y=62.00, z=175.25], EntityZombie['Zombie'/518, l='MpServer', x=203.50, y=91.00, z=156.50], EntityPig['Pig'/307, l='MpServer', x=220.71, y=63.00, z=219.39], EntityCreeper['Creeper'/306, l='MpServer', x=233.31, y=41.00, z=179.03], EntityPig['Pig'/309, l='MpServer', x=239.88, y=64.00, z=235.94], EntityPig['Pig'/311, l='MpServer', x=231.50, y=66.00, z=272.50], EntityPig['Pig'/310, l='MpServer', x=243.06, y=64.00, z=242.00], EntityPig['Pig'/313, l='MpServer', x=232.00, y=66.00, z=276.00], EntityPig['Pig'/312, l='MpServer', x=228.25, y=66.00, z=275.09], EntityMinecartChest['container.minecart'/314, l='MpServer', x=237.50, y=33.06, z=310.50], EntityPlayerSP['PCAwesomeness'/512, l='MpServer', x=239.85, y=64.00, z=234.81], EntityZombie['Zombie'/297, l='MpServer', x=232.50, y=13.00, z=166.50], EntityCreeper['Creeper'/298, l='MpServer', x=230.50, y=16.00, z=169.50], EntityCreeper['Creeper'/299, l='MpServer', x=237.50, y=28.00, z=168.50], EntityZombie['Zombie'/300, l='MpServer', x=230.84, y=13.00, z=168.31], EntityCreeper['Creeper'/301, l='MpServer', x=231.50, y=40.00, z=175.50], EntitySpider['Spider'/339, l='MpServer', x=242.28, y=40.09, z=294.16], EntityPig['Pig'/338, l='MpServer', x=239.97, y=64.00, z=242.81], EntityPig['Pig'/337, l='MpServer', x=249.00, y=65.00, z=219.63], EntityItem['item.item.dyePowder.black'/336, l='MpServer', x=255.16, y=34.00, z=198.81], EntityPig['Pig'/351, l='MpServer', x=262.50, y=69.00, z=201.94], EntityCreeper['Creeper'/350, l='MpServer', x=268.34, y=38.00, z=203.44], EntityRabbit['Rabbit'/349, l='MpServer', x=268.53, y=90.00, z=160.16], EntityBat['Bat'/348, l='MpServer', x=256.38, y=41.10, z=162.25], EntitySpider['Spider'/334, l='MpServer', x=245.50, y=46.00, z=191.50], EntityZombie['Zombie'/335, l='MpServer', x=241.97, y=35.00, z=203.41], EntitySkeleton['Skeleton'/332, l='MpServer', x=255.50, y=47.00, z=173.50], EntityBat['Bat'/333, l='MpServer', x=248.47, y=41.10, z=172.66], EntitySkeleton['Skeleton'/330, l='MpServer', x=246.50, y=43.17, z=170.50], EntitySpider['Spider'/331, l='MpServer', x=246.50, y=43.00, z=170.50], EntityCreeper['Creeper'/373, l='MpServer', x=299.50, y=70.00, z=169.50], EntitySquid['Squid'/375, l='MpServer', x=293.03, y=62.25, z=189.41], EntitySkeleton['Skeleton'/374, l='MpServer', x=297.84, y=70.00, z=170.44], EntityEnderman['Enderman'/381, l='MpServer', x=292.44, y=69.00, z=281.59], EntityZombie['Zombie'/380, l='MpServer', x=296.59, y=68.00, z=277.69], EntityZombie['Zombie'/383, l='MpServer', x=289.69, y=68.00, z=284.09], EntityZombie['Zombie'/382, l='MpServer', x=296.31, y=68.00, z=275.38], EntitySquid['Squid'/377, l='MpServer', x=290.97, y=59.53, z=181.94], EntitySquid['Squid'/376, l='MpServer', x=289.13, y=60.97, z=185.50], EntitySquid['Squid'/379, l='MpServer', x=295.16, y=59.06, z=186.19], EntitySquid['Squid'/378, l='MpServer', x=290.47, y=56.81, z=180.47], EntityPig['Pig'/352, l='MpServer', x=267.69, y=69.00, z=258.47], EntityPig['Pig'/353, l='MpServer', x=258.41, y=69.00, z=270.78], EntityZombie['Zombie'/354, l='MpServer', x=256.50, y=15.00, z=281.50], EntityPig['Pig'/364, l='MpServer', x=276.13, y=69.00, z=272.41], EntitySquid['Squid'/360, l='MpServer', x=286.28, y=59.97, z=181.16], EntityZombie['Zombie'/361, l='MpServer', x=274.34, y=33.00, z=232.34], EntityPig['Pig'/362, l='MpServer', x=282.81, y=70.00, z=272.50], EntityPig['Pig'/363, l='MpServer', x=284.50, y=69.00, z=274.50], EntityPig['Pig'/402, l='MpServer', x=316.22, y=66.00, z=306.53], EntityBat['Bat'/400, l='MpServer', x=303.53, y=22.96, z=287.64], EntitySheep['Sheep'/401, l='MpServer', x=312.25, y=67.00, z=312.13], EntityBat['Bat'/702, l='MpServer', x=181.47, y=15.91, z=212.49], EntitySheep['Sheep'/395, l='MpServer', x=315.50, y=64.00, z=232.50], EntityBat['Bat'/393, l='MpServer', x=315.56, y=14.04, z=156.45], EntityBat['Bat'/701, l='MpServer', x=187.47, y=18.10, z=214.75], EntityCreeper['Creeper'/399, l='MpServer', x=304.50, y=11.00, z=286.50], EntityPig['Pig'/387, l='MpServer', x=299.44, y=76.00, z=298.69], EntityPig['Pig'/386, l='MpServer', x=300.81, y=77.00, z=296.16], EntityZombie['Zombie'/692, l='MpServer', x=170.50, y=78.00, z=306.50], EntityPig['Pig'/385, l='MpServer', x=289.44, y=74.00, z=299.44], EntityZombie['Zombie'/693, l='MpServer', x=167.50, y=78.00, z=311.50], EntityPig['Pig'/384, l='MpServer', x=289.84, y=68.00, z=280.97], EntityPig['Pig'/388, l='MpServer', x=299.09, y=69.00, z=304.16], EntityTrail['unknown'/650, l='MpServer', x=239.85, y=64.00, z=234.81], EntitySpider['Spider'/670, l='MpServer', x=178.56, y=64.00, z=211.81], EntityCreeper['Creeper'/205, l='MpServer', x=165.50, y=16.00, z=291.50], EntitySpider['Spider'/204, l='MpServer', x=167.16, y=26.00, z=292.41], EntityCreeper['Creeper'/207, l='MpServer', x=164.50, y=48.00, z=301.50], EntityCreeper['Creeper'/206, l='MpServer', x=162.97, y=38.00, z=296.38], EntityPig['Pig'/201, l='MpServer', x=175.88, y=64.00, z=223.13], EntityBat['Bat'/200, l='MpServer', x=179.51, y=15.00, z=241.34], EntityZombie['Zombie'/202, l='MpServer', x=166.50, y=27.00, z=228.50], EntityPig['Pig'/212, l='MpServer', x=174.53, y=82.00, z=307.47], EntityPig['Pig'/213, l='MpServer', x=175.69, y=90.00, z=309.47], EntityPig['Pig'/214, l='MpServer', x=175.53, y=83.00, z=307.59], EntityZombie['Zombie'/208, l='MpServer', x=166.44, y=71.00, z=285.06], EntityPig['Pig'/209, l='MpServer', x=177.94, y=85.00, z=304.03], EntityCreeper['Creeper'/211, l='MpServer', x=168.44, y=37.00, z=305.09], EntityBat['Bat'/238, l='MpServer', x=176.46, y=12.96, z=313.50], EntityPig['Pig'/237, l='MpServer', x=186.84, y=83.00, z=305.88], EntityPig['Pig'/236, l='MpServer', x=183.53, y=87.00, z=302.53], EntityPig['Pig'/235, l='MpServer', x=180.50, y=86.00, z=297.50], EntityCreeper['Creeper'/234, l='MpServer', x=185.38, y=29.00, z=301.03], EntityCreeper['Creeper'/233, l='MpServer', x=186.50, y=18.00, z=270.50], EntityCreeper['Creeper'/232, l='MpServer', x=180.28, y=19.00, z=270.69], EntityCreeper['Creeper'/231, l='MpServer', x=175.56, y=18.00, z=269.03], EntitySpider['Spider'/230, l='MpServer', x=195.38, y=12.00, z=259.06], EntityPig['Pig'/229, l='MpServer', x=184.16, y=64.00, z=232.72], EntityPig['Pig'/228, l='MpServer', x=177.13, y=65.00, z=242.31], EntityPig['Pig'/227, l='MpServer', x=182.81, y=64.00, z=229.34], EntityPig['Pig'/226, l='MpServer', x=195.28, y=67.00, z=223.47], EntityCreeper['Creeper'/225, l='MpServer', x=189.91, y=25.00, z=163.56], EntitySheep['Sheep'/254, l='MpServer', x=202.44, y=70.00, z=287.53], EntitySheep['Sheep'/255, l='MpServer', x=202.94, y=75.00, z=283.13], EntitySkeleton['Skeleton'/252, l='MpServer', x=205.47, y=22.00, z=259.97], EntityZombie['Zombie'/253, l='MpServer', x=206.34, y=23.00, z=250.34], EntityPig['Pig'/250, l='MpServer', x=197.91, y=63.00, z=235.09], EntitySkeleton['Skeleton'/251, l='MpServer', x=205.50, y=23.00, z=250.50], EntityPig['Pig'/248, l='MpServer', x=193.44, y=66.91, z=223.47], EntityPig['Pig'/249, l='MpServer', x=193.84, y=69.00, z=208.03], EntityPig['Pig'/247, l='MpServer', x=203.66, y=64.00, z=190.13]]
 Retry entities: 0 total; []
 Server brand: fml,forge
 Server type: Integrated singleplayer server
Stacktrace:
 at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
 at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2488)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
 at net.minecraft.client.main.Main.main(SourceFile:120)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
 at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
 at org.multimc.EntryPoint.listen(EntryPoint.java:165)
 at org.multimc.EntryPoint.main(EntryPoint.java:54)[/p]
-- System Details --
Details:
 Minecraft Version: 1.8
 Operating System: Windows 7 (amd64) version 6.1
 Java Version: 1.7.0_67, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 357329640 bytes (340 MB) / 658505728 bytes (628 MB) up to 954728448 bytes (910 MB)
 JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
 IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
 FML: MCP v9.10 FML v8.0.76.1392 Minecraft Forge 11.14.1.1392 6 mods loaded, 6 mods active
 mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
 FML{8.0.76.1392} [Forge Mod Loader] (forge-1.8-11.14.1.1392-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
 Forge{11.14.1.1392} [Minecraft Forge] (forge-1.8-11.14.1.1392-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
 DamageIndicatorsMod{3.3.3} [Damage Indicators] ([1.8]DamageIndicatorsMod-3.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
 iChunUtil{5.3.0} [iChunUtil] (iChunUtil-5.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
 Tabula{5.0.0} [Tabula] (Tabula-5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
 Loaded coremods (and transformers): 
 Launched Version: 1.8
 LWJGL: 2.9.1
 OpenGL: AMD Radeon(TM) HD 6520G GL version 4.1.11159 Compatibility Profile Context, ATI Technologies Inc.
 GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.[/p]
[p]Using VBOs: No
 Is Modded: Definitely; Client brand changed to 'fml,forge'
 Type: Client (map_client.txt)
 Resource Packs: []
 Current Language: English (US)
 Profiler Position: N/A (disabled)

**Comment by iChun** [comment]
Try using iChunUtil 5.2.0 or earlier. There were some changes with the Tabula format in 5.3.0 but there hasn't been an update pushed to Tabula to support that yet. Also make sure you're not using the deobf builds in an obf environment and vice versa

**Comment by PCAwesomeness** [comment]
OK!
