### ISSUE TITLE
I am having a crash in my dev (1.8)

### ISSUE THREAD

**Issue by bluemonster122** [iChun/Tabula#61]
I have installed Tabula 5.0.0-deobf, and iChunUtil 5.2.0-deobf, put them both in the mods folder, and when i launch the client it comes up with this...
http://pastebin.com/s1fV4Htm

**Comment by bluemonster122** [comment]
http://pastebin.com/s1fV4Htm

**Comment by iChun** [comment]
Update the mappings that forge uses and redecompile with the updated
mappings

**Comment by bluemonster122** [comment]
How do I update the mappings? I am unfamiliar with this

**Comment by bluemonster122** [comment]
I have updated the mappings (to " mappings = "snapshot_20150509") and redecompiled and its still throwing the same error

**Comment by bluemonster122** [comment]
I updated my mappings (mappings = "stable_16") and redecompiles, but it is still throwing the same bug

**Comment by iChun** [comment]
did you reimport your gradle project?

**Comment by bluemonster122** [comment]
yes

**Comment by bluemonster122** [comment]
I have found a way around it, but its tedious. I am useing the runClient method in gradle to launch the client... but at least I found a way that works hey =D

**Comment by bluemonster122** [comment]
I don't know what I did, but it is working now. =D
