### ISSUE TITLE
Crash Rotations

### ISSUE THREAD

**Issue by T4ge** [iChun/Tabula#64]
http://pastebin.com/Bxi41smW

Got this crash.
Managed to do it multiple times.
Simply make a block/model, select it.
Empty one of the rotation options completely.
Leave no numbers.
Press Tab until it selects the name and then Enter.
Which yields a crash.
Found it during a miss click happily early on a model so it cause me no distress.

**Comment by iChun** [comment]
Try updating to the 1.8 version

**Comment by T4ge** [comment]
I'll try it when the mods in my pack moves to 1.8 ^^
