### ISSUE TITLE
Make MC scale actually scale.

### ISSUE THREAD

**Issue by gravityfox** [iChun/Tabula#78]
I'm not entirely sure what the MC Scale is supposed to do (I assumed a uniform shape scale), but it certainly doesn't "scale" the cube.

Rather, it adds or subtracts to the dimensions of the shape, making it warp cuboids that aren't perfect cubes. If you increase it, the shapes become roughly cube shaped, but decreasing it can make shapes flip inside out and become thin as a pole. This makes it rather useless as a scale for anything other than a perfect cube.

A quick test reveals that a 2x3x4 cube with MC Scale of 1.0 becomes a 3x4x5 cube. 

The regular scale parameters work fine, but it's just annoying having to enter the same scaling values 3 times. If this is the intended behavior of MC Scale, do you think you could add a toggle to lock the xyz scale values together?

**Comment by iChun** [comment]
MC scale is something put in minecraft. There's nothing I can change to fix
this as it's a minecraft model characteristic when creating a box, not
Tabula's. That is why there is a separate scale input for Tabula's scaling

**Comment by gravitythief** [comment]
Then can you make a toggle lock to make the scaling easier?

**Comment by iChun** [comment]
I can, but it's not high up on the priority list so don't expect to see a
feature/config for it for quite a while

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
