### ISSUE TITLE
Not importing every model in render file

### ISSUE THREAD

**Issue by ZornTaov** [iChun/Tabula#79]
I put multiple private ModelBase greenHead = new ModelRideArmorHead(); into my renderer for each body part, and tabula is only listing the last one in the "Import From Minecraft" menu.

Using iChunUtils 4.2.2 and Tabula 4.1.1 with minecraft forge 1.7.10-10.13.4.1448 and source for the code used is here https://github.com/ZornTaov/ReploidCraft/blob/master/src/main/java/zornco/reploidcraft/client/renderers/RenderRideArmor.java

**Comment by iChun** [comment]
I have a feeling you've not ported this mod to 1.8 to test on the 1.8
version

**Comment by ZornTaov** [comment]
I have obviously not ported the mod to 1.8 yet, but seeing as the majority of work for minecraft is focused on 1.8 I'll try and port it now and see if anything changes.  I'll post here once I've gotten everything to work then.
