### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [iChun/Tabula#85]
I'm new to Tabula and I've done some research but haven't found anything on my question. If I want to make my texture map larger than what is generated how do I go about doing so? for example, if I make an arm a 2x2x5, that's how many pixels the texture is, is there a way to make that larger? for HD textures? or detailed textures?

**Comment by EPIICTHUNDERCAT** [comment]
Thanks ichun!

**Comment by iChun** [comment]
I think it's under edit project and edit textures or something along those lines. It should be somewhere there. If you want to use HD textures just make your texture scalable to what's set and that should be fine. let me know if you have trouble finding it.
