### ISSUE TITLE
Using .tbl for hats mod

### ISSUE THREAD

**Issue by AmyMialee** [iChun/Tabula#86]
Is there any way to use the tabula files (.tbl) with the hats mod?
If not is there a converter for it to a format that does?
And would a feature like this be added ever?

**Comment by iChun** [comment]
Do they not already use .tbl? Or is that on some unreleased build :V

**Comment by XxLegoTadhgxX** [comment]
I have tried putting a tbl file in the folder (a twitchtv hat I made) but it won't show up anywhere on the list

**Comment by iChun** [comment]
I'll double check this for the update to 1.10 then.

**Comment by XxLegoTadhgxX** [comment]
But Will there be any way to play with tbl files in 1.7.10 modpacks?

**Comment by iChun** [comment]
Other than making your own build which uses .tbl models, no. Though it
wouldn't be hard, it's just a matter of changing the format that Hats looks
for, and *.tc2 and *.tbl uses the same loader and they're both loaded into
the game as the same format.

I'm trying to push for 1.10.2 use so I won't be working on my 1.7.10 mods
anymore.

**Comment by XxLegoTadhgxX** [comment]
I might try but having 0 knowledge in this field I will most likely fail, worth a shot though, thanks
