### ISSUE TITLE
Cannot setup repository

### ISSUE THREAD

**Issue by DaBigJoe** [iChun/Tabula#89]
I've tried but for the life of me I cannot get a local copy of this repo working. I'm developing an animation system for Minecraft, the [Obsidian Animator](https://github.com/DaBigJoe/ObsidianSuite), and I would like to add Tabula model support, so I thought it would be useful to have a working repo of Tabula for reference. I can do without, but I wanted to try since it'll make it easier. 

Anyway, I tried following the tutorial on the [iChunUtil repo](https://github.com/iChun/iChunUtil), but I couldn't set up that repo. The README says it needs the 'Morph API', but I could not find that anywhere. It was also saying the access transformers were broken.

The only thing I needed to build the iChunUtil repo for was to get the deobf jar, but those are available online, so I tried using iChunUtil-5.1.0-deobf.jar since that is the version in the build.gradle file for this repo (and I assume the version Tabula uses), by placing it in /libs. I managed to then build the Tabula project and get it setup in Eclipse, but I had missing imports. The iChunUtil deobf jar is definitely on the build path, and some of the imports work fine, but others are missing, for example
'us.ichun.mods.ichunutil.common.module.tabula.client.formats.types.Exporter'

I allow have some issues about methods/fields not being visible, I assume that's down to the access transformer(s). There's a few pointers on sorting that in the iChunUtil repo, but I didn't bother trying that as it's pointless without having the imports working. 

Any help would be much appreciated, either via a setup guide or just some points as to where I was going wrong. I found [this post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/2496959-help-with-compiling-a-certain-mods-source-code?page=2) where someone has tried to do something similar before, but it didn't help all that much. Cheers!

**Comment by iChun** [comment]
Sorry, will read the rest in a bit, just getting off a plane now.

The Morph API is in the Morph repository in the 1.8 branch but it doesn't
compile properly, there is like, one erroring line or something like that
so just remove that line, an ability reference IIRC.

I'll read and respond to the rest later.

**Comment by DaBigJoe** [comment]
Ahh thank you, that helped, I managed to build the iChunUtil deobf jar built using the Morph API from the 1.8 branch. 

Still no luck with this repo though, I tried using the jar produced from the iChunUtil repo with no change.

**Comment by DaBigJoe** [comment]
So after some more tinkering, I managed to get this repo setup. I had to rollback several commits to the [stable 1.8 version](https://github.com/iChun/Tabula/commit/6034b45f409f49931476d55a20856dae00516a8b), and put the iChunUtil v5.5.0 deobf jar in the libs folder. Also, I had to copy the META-INF folder from that jar into src/api/resources as outline in the iChunUtil README. All working now :)
