### ISSUE TITLE
Crash when dragging a piece off of another piece.

### ISSUE THREAD

**Issue by wiiv** [iChun/Tabula#94]
crash report.
https://pastebin.com/hqMPVWXi

I getting another issue, when I use the arrows to adjust a piece's size or position, sometimes (mostly on the first click of that arrow) it jumps for twice the value it should. (5 to 7, or 0.10 to 0.30).

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
