### ISSUE TITLE
Appearance of cubes untextured

### ISSUE THREAD

**Issue by Spyeedy** [iChun/Tabula#95]
I find the bright appearances of the cube in 1.10.2 and 1.12.2hard to see, I preferred the 1.8 appearance of the cubes where they weren't so bright. Perhaps you could make it an option between the 2 appearances?

**1.8 Cube Appearance**
http://prntscr.com/he67u1

**1.12.2 Cube Appearance**
http://prntscr.com/he68m7

As you can see in the different pictures, in 1.8, it was easier to see the different cubes' sizes due to different colors on the sides of the cube unlike in 1.12.2 where it was all white and made it difficult to see each cubes.

**Comment by iChun** [comment]
Woah wait that's actually a bug. Something disabled GL_NORMALIZE. I don't
know when I can fix this though, I'm not doing any development till
January.

**Comment by Spyeedy** [comment]
Wha? It's a bug? OO, I thought it wasn't a bug but something you changed with... haha, sorry 😅 . Anyway, alright. That's fine with me. We all need breaks 😄

**Comment by iChun** [comment]
I forgot to ask. Does this happen without any mods installed other than iChunUtil and Tabula?

**Comment by Spyeedy** [comment]
Yes, this happens when running with iChunUtil and Tabula.
`iChunUtil-1.12.2-7.0.1
Tabula-1.12.2-7.0.0`

**Comment by SteveOriginal** [comment]
Yeah, I have this too...

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
