### ISSUE TITLE
Suggestion: Option to change background color & grid color

### ISSUE THREAD

**Issue by NaEve** [iChun/Tabula#98]
Hey, 

First of all: Awesome Mod! I have a suggestion to improve modelling with it: Add an option to change the color of the background and the grid. This way we can get an idea of how our models will look on dark or green backgrounds etc. without the need to export them first.

Keep up the good work!
Best, eva

edit: Sorry .. just found the theme selector. Though it does not contain specific custom options, it's already a great help to view the model on dark backgrounds.

**Comment by iChun** [comment]
Check out themes for Tabula. It's already a thing. It's one of the top
buttons and you can make your own themes.
